from backend.recommendations.registry import rule

RULES = [
    rule(
        "accessibility.add_form_labels",
        "Accessibility",
        "Add labels to form controls",
        "Associate an accessible name with form fields that currently have no label.",
        "Form controls without an associated label or accessible name cannot be identified by assistive technology.",
        (
            "Associate a label element, or provide aria-label / aria-labelledby, for each unnamed field.",
            "Prefer a visible label that stays associated with the control.",
            "Confirm submit controls also expose an accessible name.",
        ),
        ("accessibility.form.label.missing", "accessibility.form.003"),
        effort="small",
        impact="high",
    ),
    rule(
        "accessibility.add_image_alt_text",
        "Accessibility",
        "Add alternative text to images",
        "Provide alternative text for images, image buttons, and linked images that currently have none.",
        "Images without an alt attribute have no text equivalent for assistive technology.",
        (
            "Add meaningful alt text for informative images.",
            "Use empty alt text only for decorative images.",
            "Ensure image buttons and linked images expose an accessible name.",
        ),
        ("accessibility.img.001", "accessibility.img.003", "accessibility.img.004"),
        effort="small",
        impact="high",
    ),
    rule(
        "accessibility.fix_color_contrast",
        "Accessibility",
        "Fix low color contrast",
        "Increase contrast for text that does not meet the scanned contrast threshold.",
        "Low contrast text is harder to read. Contrast findings come from the accessibility analyzer, not from visual guessing.",
        (
            "Identify text reported with insufficient contrast.",
            "Adjust foreground or background color so the text meets the referenced contrast criterion.",
            "Recheck the same components after the change.",
        ),
        ("accessibility.contrast.001",),
        effort="medium",
        impact="high",
    ),
    rule(
        "accessibility.add_accessible_button_name",
        "Accessibility",
        "Add accessible names to buttons",
        "Give every button an accessible name.",
        "Buttons without an accessible name cannot be identified by assistive technology.",
        (
            "Add visible text, aria-label, or labelled images inside unnamed buttons.",
            "Avoid icon-only buttons with no accessible name.",
            "Verify the name describes the action the button performs.",
        ),
        ("accessibility.button.name.missing",),
        effort="small",
        impact="high",
    ),
    rule(
        "accessibility.add_accessible_link_name",
        "Accessibility",
        "Add accessible names to links",
        "Provide accessible names for links that currently have none.",
        "Links without an accessible name do not communicate their destination or purpose.",
        (
            "Add visible text, aria-label, or an image with alt text inside unnamed links.",
            "Prefer link text that describes the destination.",
            "Remove empty anchors that are not intended to be links.",
        ),
        ("accessibility.link.001",),
        effort="small",
        impact="high",
    ),
    rule(
        "accessibility.add_document_language",
        "Accessibility",
        "Declare the page language",
        "Add a valid lang attribute on pages that do not declare a document language.",
        "Assistive technologies use the language attribute to select pronunciation.",
        (
            "Set lang on the html element to a valid BCP 47 tag for the page language.",
            "Do not leave the lang attribute empty.",
            "English is not required; use the actual language of the page.",
        ),
        ("accessibility.doc.001", "accessibility.doc.003"),
        effort="small",
        impact="medium",
    ),
    rule(
        "accessibility.improve_heading_structure",
        "Accessibility",
        "Improve accessible heading structure",
        "Add or repair headings that are missing, empty, or skipped in the outline.",
        "Headings outline the page for assistive technology. Empty or skipped headings weaken that outline.",
        (
            "Add headings where the page currently has none.",
            "Give headings accessible text and avoid aria-hidden on visible headings.",
            "Avoid skipping heading levels when outlining content.",
        ),
        ("accessibility.head.001", "accessibility.head.002", "accessibility.head.003"),
        effort="medium",
        impact="medium",
    ),
]
