from backend.recommendations.registry import rule

RULES = [
    rule(
        "aeo.clarify_organization_identity",
        "AEO",
        "Clarify the organization or brand name",
        "State the organization, brand, or site name clearly on pages where no usable identity was found.",
        "Answer systems need a stable name to associate a page with an organization or brand. This is an identity observation, not a prediction of AI citation.",
        (
            "Place the organization or brand name in visible page content such as the title, heading, or header.",
            "Describe what the organization does in nearby text.",
            "Keep the visible name consistent with any Organization structured data.",
        ),
        ("aeo.entity.001",),
        effort="small",
        impact="medium",
    ),
    rule(
        "aeo.add_organization_entity",
        "AEO",
        "Add Organization structured data",
        "Add Organization markup on pages where an organization entity was not detected.",
        "Organization structured data makes the entity behind a site explicit for machine readers. This does not predict rich results or AI citations.",
        (
            "Add Organization JSON-LD (or equivalent) with a name property.",
            "Include a URL that matches the site identity where available.",
            "Keep the schema name consistent with the visible brand name.",
        ),
        ("aeo.entity.organization.missing",),
        effort="medium",
        impact="medium",
    ),
    rule(
        "aeo.improve_answer_structure",
        "AEO",
        "Improve question-and-answer structure",
        "Place a concise answer immediately after question-style headings on pages that lack extractable answer blocks.",
        "A short paragraph after a question heading is an extractable question/answer pair. This is a content-structure observation, not evidence of AI selection.",
        (
            "Identify question-style headings on the affected pages.",
            "Follow each question with a concise direct answer in the next paragraph.",
            "Keep the first sentence specific to the question asked.",
        ),
        ("aeo.answer.001",),
        effort="medium",
        impact="medium",
    ),
    rule(
        "aeo.add_question_based_sections",
        "AEO",
        "Add question-based headings",
        "Add useful question-style headings on pages that currently have none.",
        "Question-oriented headings make the relationship between a question and an answer explicit for automated readers.",
        (
            "Identify questions users actually ask about the page subject.",
            "Add headings that state those questions.",
            "Follow each heading with a concise answer.",
        ),
        ("aeo.question.001",),
        effort="medium",
        impact="medium",
    ),
    rule(
        "aeo.add_faq_content",
        "AEO",
        "Add FAQ content where it fits the page",
        "Add an FAQ section or FAQPage markup on pages that have no repeated question/answer structure.",
        "FAQ sections and FAQPage schema expose explicit question/answer groups. FAQ schema is not required for every site.",
        (
            "Add a visible FAQ section only if the page subject has recurring questions.",
            "Pair each question with a concise answer.",
            "If using FAQPage schema, keep it aligned with the visible questions.",
        ),
        ("aeo.question.002",),
        effort="medium",
        impact="low",
        priority_cap="medium",
    ),
    rule(
        "aeo.add_authorship_information",
        "AEO",
        "Add authorship information",
        "Add visible author information on article-like pages where authorship was not detected.",
        "Authorship is an observable identity signal for article-like pages. Missing author information is not proof of low quality.",
        (
            "Add a visible byline on article-like pages.",
            "Include author markup if the page already uses Article structured data.",
            "Keep visible and schema author names consistent.",
        ),
        ("aeo.author.001",),
        effort="small",
        impact="medium",
    ),
]
