from backend.recommendations.registry import rule

RULES = [
    rule(
        "cro.improve_primary_cta_visibility",
        "CRO",
        "Keep the primary conversion action visible",
        "Place the primary call-to-action where it is visible in the initial viewport.",
        "SiteLens measured a conversion action that is not visible in the initial viewport. This is an observable layout signal, not a conversion-rate prediction.",
        (
            "Identify the intended primary conversion action on the affected page.",
            "Keep that control unclipped and visible in the initial desktop and mobile viewports.",
            "Recheck the same SiteLens viewports after layout changes.",
        ),
        ("cro.cta.primary.not_visible", "cro.mobile.cta.not_visible"),
        effort="medium",
        impact="high",
    ),
    rule(
        "cro.add_primary_cta",
        "CRO",
        "Add a clear primary conversion action",
        "Add a clearly worded conversion action on pages that present an offer.",
        "No primary CTA met SiteLens's detection threshold on the affected pages. Absence of a detected CTA is not proof that conversions will fail.",
        (
            "Decide whether the page has an intended next step.",
            "If it does, present that step as a visible button or link with specific action wording.",
            "Avoid unlabeled or javascript-only controls.",
        ),
        ("cro.cta.primary.missing", "cro.value_proposition.cta_missing"),
        effort="medium",
        impact="medium",
    ),
    rule(
        "cro.clarify_cta_text",
        "CRO",
        "Clarify call-to-action wording",
        "Replace generic CTA labels with wording that names the next step.",
        "Generic labels such as Submit or Click Here were detected without enough surrounding context.",
        (
            "Replace generic control text with the action the user will take.",
            "Keep repeated conversion actions consistent across the page.",
            "Recheck the labels after publishing.",
        ),
        ("cro.cta.text.vague", "cro.form.submit_unclear", "cro.cta.inconsistent_label"),
        effort="small",
        impact="medium",
    ),
    rule(
        "cro.reduce_form_friction",
        "CRO",
        "Reduce form interaction effort",
        "Review long forms and unclear submit controls that add interaction effort.",
        "Form field counts and submit wording are observable friction signals. They are not proof that conversion will decrease.",
        (
            "Count the visible fields on the affected form.",
            "Remove fields that are not needed for the form's inferred purpose, if that is appropriate.",
            "Give the submit control specific wording.",
        ),
        ("cro.form.large", "cro.form.submit_unclear", "cro.form.unclear_purpose"),
        effort="medium",
        impact="medium",
    ),
    rule(
        "cro.clarify_value_proposition",
        "CRO",
        "Clarify the visible value proposition",
        "Use a heading and supporting text that name the product or service.",
        "Value proposition checks look for a heading, supporting description, and a nearby action. They do not judge commercial quality.",
        (
            "Write a heading that names the offer and audience where that is the page's purpose.",
            "Add a short supporting description near the heading.",
            "Place a conversion action with the value proposition when the page has a next step.",
        ),
        ("cro.value_proposition.h1_missing", "cro.value_proposition.supporting_text_missing"),
        effort="medium",
        impact="medium",
    ),
    rule(
        "cro.resolve_conversion_path",
        "CRO",
        "Connect pages to a conversion destination",
        "Provide an observable internal path toward a contact, signup, or offer page.",
        "No conversion path could be determined from crawled internal links. This is a graph observation, not a funnel prediction.",
        (
            "Link offer pages to a contact, signup, or pricing destination that exists on the site.",
            "Use crawlable href values rather than empty or javascript-only actions.",
            "Recrawl after publishing the links.",
        ),
        ("cro.conversion_path.unresolved", "cro.cta.destination.unresolved"),
        effort="medium",
        impact="medium",
    ),
    rule(
        "cro.review_overlay_coverage",
        "CRO",
        "Review overlays covering conversion actions",
        "Reduce overlays that cover a primary call-to-action on first paint.",
        "An overlay was measured covering a conversion action in the initial viewport. Coverage is an observable layout fact.",
        (
            "Identify overlays present in the initial viewport.",
            "Ensure the overlay does not cover the primary conversion action.",
            "Provide a way to dismiss the overlay without hiding the action.",
        ),
        ("cro.overlay.cta.covered",),
        effort="medium",
        impact="medium",
    ),
    rule(
        "cro.add_contact_method",
        "CRO",
        "Add a visible contact method",
        "Provide a contact page, form, email, or phone number that is observable in the crawl.",
        "No obvious contact method was detected on the page or elsewhere in the crawled site.",
        (
            "Add a contact destination that can be crawled.",
            "Link to it from pages that present an offer.",
            "Keep at least one method visible without authentication.",
        ),
        ("cro.contact.method.missing",),
        effort="small",
        impact="medium",
    ),
]
