from backend.recommendations.registry import rule

RULES = [
    rule(
        "performance.reduce_javascript",
        "Performance",
        "Reduce JavaScript payload",
        "Reduce JavaScript transfer size on pages where the scanned payload exceeds the configured threshold.",
        "Large JavaScript transfer increases download and parse cost. Size alone is not a failure of the page, but it is an observable delivery issue.",
        (
            "Identify large JavaScript resources reported in the performance findings.",
            "Split bundles, remove unused code, and defer non-critical scripts.",
            "Recheck transfer size after the change. This does not predict ranking or conversion outcomes.",
        ),
        ("performance.javascript.large_payload",),
        effort="medium",
        impact="high",
    ),
    rule(
        "performance.reduce_render_blocking",
        "Performance",
        "Reduce render-blocking resources",
        "Defer or async scripts and non-critical CSS that block initial rendering.",
        "Synchronous scripts in the document head and render-blocking CSS delay first render. This is a loading-order observation from the scanned page.",
        (
            "Identify parser-blocking scripts and render-blocking CSS in the document head.",
            "Add async or defer to non-critical scripts.",
            "Load non-critical CSS in a non-blocking way where the page still remains usable.",
        ),
        ("performance.js.001", "performance.block.001"),
        effort="medium",
        impact="medium",
    ),
    rule(
        "performance.optimize_images",
        "Performance",
        "Optimize oversized images",
        "Compress and resize images whose transfer size or natural dimensions exceed the configured thresholds.",
        "Oversized images increase bytes transferred relative to how they are displayed. File size alone is not an automatic failure.",
        (
            "Identify images that exceed the configured transfer or dimension thresholds.",
            "Compress images and convert them to an appropriate modern format where supported.",
            "Resize images closer to their rendered dimensions or provide responsive variants.",
            "Do not treat this as a ranking or revenue prediction.",
        ),
        ("performance.image.large", "performance.img.002"),
        effort="medium",
        impact="high",
    ),
    rule(
        "performance.enable_lazy_loading",
        "Performance",
        "Lazy-load below-the-fold images",
        "Add loading=\"lazy\" to offscreen images. Do not lazy-load a confirmed Largest Contentful Paint image.",
        "Below-the-fold images that load eagerly compete with above-the-fold resources. The scanner excludes a confirmed LCP image from this finding when that evidence is available.",
        (
            "Identify below-the-fold images that do not use loading=\"lazy\".",
            "Add lazy loading to those offscreen images.",
            "If an image is identified as the Largest Contentful Paint image, keep it eager and do not lazy-load it.",
            "If LCP evidence is unavailable, apply lazy loading only to images that are clearly below the fold.",
        ),
        ("performance.img.003",),
        effort="small",
        impact="medium",
    ),
    rule(
        "performance.review_third_party_resources",
        "Performance",
        "Review third-party resources",
        "Review third-party scripts and assets whose transfer size is large relative to first-party content.",
        "Third-party means a different registrable domain, not that the resource is malicious. Large third-party transfer can delay page work.",
        (
            "Identify third-party hosts contributing the most transfer.",
            "Remove unused embeds and load remaining third-party scripts after critical content where possible.",
            "This is not a security classification of those hosts.",
        ),
        ("performance.tp.001",),
        effort="medium",
        impact="medium",
    ),
    rule(
        "performance.improve_caching",
        "Performance",
        "Improve static asset caching",
        "Add cache-related headers on static assets that currently expose none.",
        "Static resources without cache headers may be re-downloaded on repeat visits. HTML and personalized responses are not required to be cached.",
        (
            "Identify static assets missing cache-related headers.",
            "Set appropriate Cache-Control or Expires values for those assets.",
            "Do not cache personalized HTML solely to satisfy this finding.",
        ),
        ("performance.cache.001",),
        effort="small",
        impact="medium",
    ),
    rule(
        "performance.enable_compression",
        "Performance",
        "Enable text compression",
        "Enable compression on text resources that are large enough to benefit and currently advertise none.",
        "Text resources without content-encoding take more bytes to transfer. Images and video are not expected to use gzip.",
        (
            "Enable gzip or brotli for HTML, CSS, JavaScript, and other text responses.",
            "Confirm content-encoding is present on the affected resources.",
            "Do not force compression on already-compressed image or video files.",
        ),
        ("performance.comp.001",),
        effort="small",
        impact="medium",
    ),
]
