from backend.recommendations.registry import rule

RULES = [
    rule(
        "seo.fix_missing_title",
        "SEO",
        "Add unique page titles",
        "Add a descriptive HTML title to pages where the title element is missing or empty.",
        "Page titles help users and search systems identify the subject of a page. Several scanned pages currently have no usable title element.",
        (
            "Add a unique <title> element on each affected page template.",
            "Describe the primary subject of the page in the title text.",
            "Keep the title concise and avoid leaving the element empty.",
            "Avoid duplicating the same title across unrelated pages.",
        ),
        ("seo.title.missing",),
        effort="small",
        impact="high",
    ),
    rule(
        "seo.optimize_title",
        "SEO",
        "Optimize page title length and wording",
        "Revise titles that are unusually short, unusually long, or generic placeholders.",
        "Title length and wording affect how a page is identified in browser tabs and search result displays. These are display and clarity issues, not ranking predictions.",
        (
            "Review titles that are shorter than typical display length or long enough to truncate.",
            "Replace generic placeholders such as Home or Untitled with a page-specific description.",
            "Keep each title unique to the page it represents.",
        ),
        ("seo.title.002", "seo.title.004"),
        effort="small",
        impact="medium",
    ),
    rule(
        "seo.add_meta_description",
        "SEO",
        "Add missing meta descriptions",
        "Add a unique meta description on pages where the description element is missing or empty.",
        "Meta descriptions summarize the page for users in search listings. Affected pages currently have no usable description content.",
        (
            "Add a <meta name=\"description\"> element on each affected template.",
            "Summarize the primary subject of the page in one or two sentences.",
            "Do not leave the content attribute empty.",
        ),
        ("seo.meta_description.missing", "seo.meta.002"),
        effort="small",
        impact="medium",
    ),
    rule(
        "seo.optimize_meta_description",
        "SEO",
        "Optimize meta description length",
        "Adjust meta descriptions that are unusually short or long compared with common display guidelines.",
        "Very short or very long descriptions may be truncated or provide little context in search listings. Length is a display guideline, not a ranking rule.",
        (
            "Review the current description length on affected pages.",
            "Write a concise summary of the page subject.",
            "Avoid repeating the title verbatim as the only description text.",
        ),
        ("seo.meta.003",),
        effort="small",
        impact="low",
    ),
    rule(
        "seo.add_primary_heading",
        "SEO",
        "Add a primary heading",
        "Add a non-empty H1 heading on pages that currently have none.",
        "An H1 heading helps people and crawlers understand the main topic of a page.",
        (
            "Add one clear H1 that describes the main topic of the page.",
            "Keep the H1 visible and non-empty.",
            "Align the H1 with the page title where they describe the same subject.",
        ),
        ("seo.h1.001",),
        effort="small",
        impact="medium",
    ),
    rule(
        "seo.simplify_heading_structure",
        "SEO",
        "Clarify heading structure",
        "Review pages with multiple H1 elements, empty H1s, or missing section headings.",
        "Heading structure communicates the outline of a page. Multiple or empty H1s and missing H2s make that outline harder to follow.",
        (
            "Give every H1 visible text that describes the page or section.",
            "Use a single primary H1 unless additional H1s are intentional and clear.",
            "Add H2 headings for distinct sections where the page has substantial content.",
        ),
        ("seo.h1.002", "seo.h1.003", "seo.h2.001", "seo.head.001"),
        effort="medium",
        impact="medium",
    ),
    rule(
        "seo.add_canonical",
        "SEO",
        "Add canonical URLs",
        "Add a canonical link on pages that currently have none.",
        "A canonical URL identifies the preferred address for a page when variants exist.",
        (
            "Add a <link rel=\"canonical\"> element on each affected template.",
            "Point the canonical URL at the preferred http(s) address for the page.",
            "Use the same canonical strategy across equivalent templates.",
        ),
        ("seo.canonical.missing",),
        effort="small",
        impact="medium",
    ),
    rule(
        "seo.fix_canonical",
        "SEO",
        "Fix canonical URLs",
        "Correct canonical links that are malformed or inconsistent with the scanned page URL.",
        "Canonical URLs that are invalid or point at a different address can send conflicting signals about the preferred page URL.",
        (
            "Use a well-formed absolute http(s) URL in rel=canonical.",
            "Confirm the canonical target is the intended preferred URL.",
            "Remove spaces or incomplete values from the canonical href.",
        ),
        ("seo.can.002", "seo.can.003"),
        effort="small",
        impact="medium",
    ),
    rule(
        "seo.add_image_alt_text",
        "SEO",
        "Add image alt attributes",
        "Add alt attributes to images that currently have none.",
        "Alternative text describes images when they cannot be seen and provides a text equivalent for image content.",
        (
            "Add an alt attribute on each image that is missing one.",
            "Describe informative images; use empty alt text only for decorative images.",
            "Do not rely on the title attribute as a substitute for alt.",
        ),
        ("seo.img.001",),
        effort="small",
        impact="medium",
    ),
    rule(
        "seo.fix_empty_internal_links",
        "SEO",
        "Fix empty or invalid links",
        "Give every link a usable destination, or remove anchors that are not links.",
        "Empty or invalid href values do not lead anywhere useful for users or crawlers.",
        (
            "Identify anchors with empty, javascript:, or otherwise invalid href values.",
            "Replace them with real destinations or remove the unused anchors.",
            "Keep fragment-only links only when they target an on-page destination.",
        ),
        ("seo.link.003",),
        effort="small",
        impact="medium",
    ),
    rule(
        "seo.improve_internal_links",
        "SEO",
        "Add internal links from pages that have none",
        "Link to related pages on the same site from pages that currently expose no internal links.",
        "Internal links help people and crawlers move between pages on the same site.",
        (
            "Identify important destination pages that should be reachable from the affected page.",
            "Add contextual or navigation links to those pages.",
            "Avoid empty href values when adding the new links.",
        ),
        ("seo.link.001",),
        effort="medium",
        impact="medium",
    ),
]
