from backend.recommendations.registry import rule

RULES = [
    rule(
        "trust.add_organization_identity",
        "Trust",
        "Add observable organization identity",
        "Publish a visible organization name and Organization structured data where that information is public.",
        "Organization identity signals were not detected within the crawled pages. This is a coverage finding, not a legitimacy determination.",
        (
            "Add the organization name in the header or footer.",
            "Provide an About or company page that can be crawled.",
            "Add Organization structured data that matches the visible name.",
        ),
        ("trust.identity.organization.missing",),
        effort="medium",
        impact="medium",
    ),
    rule(
        "trust.add_contact_information",
        "Trust",
        "Add a visible contact method",
        "Provide a crawlable contact page or another visible contact method.",
        "No dedicated contact page was detected within the crawled pages. Missing detection is limited to the SiteLens crawl.",
        (
            "Publish a contact page, email, phone number, or form that can be crawled.",
            "Link to that destination from the header, footer, or homepage.",
            "Keep at least one method visible without authentication.",
        ),
        ("trust.contact.page.missing", "trust.contact.page.methods"),
        effort="small",
        impact="medium",
    ),
    rule(
        "trust.add_privacy_policy_link",
        "Trust",
        "Add a discoverable privacy policy link",
        "Link a privacy policy from the footer or navigation if a policy is published.",
        "No privacy policy page was detected within the crawled pages. This does not assess legal compliance.",
        (
            "Publish a privacy policy page if one exists.",
            "Link it from the footer or navigation using crawlable href values.",
            "Recrawl after publishing the link.",
        ),
        ("trust.policy.privacy.missing",),
        effort="small",
        impact="medium",
    ),
    rule(
        "trust.add_about_page",
        "Trust",
        "Add a crawlable About page",
        "Publish an About, Company, or Our Story page if that information is intended to be public.",
        "No dedicated About page was detected within the crawled pages.",
        (
            "Create an About or company page.",
            "Link it from primary navigation or the footer.",
            "Keep the destination crawlable.",
        ),
        ("trust.about.page.missing",),
        effort="small",
        impact="low",
    ),
    rule(
        "trust.add_author_information",
        "Trust",
        "Add author information on articles",
        "Add a visible author name and publication date on article pages.",
        "Author information was not detected on one or more article pages. This does not judge article accuracy.",
        (
            "Add a visible byline on article pages.",
            "Include a publication or last-updated date.",
            "Where applicable, add Person structured data that matches the visible author.",
        ),
        ("trust.authorship.author.missing", "trust.authorship.date.missing"),
        effort="small",
        impact="medium",
    ),
    rule(
        "trust.review_entity_consistency",
        "Trust",
        "Review organization name consistency",
        "Align visible brand names with Organization structured data and footer identity.",
        "Potential entity-name inconsistency was detected between visible content and structured data. SiteLens does not determine which value is correct.",
        (
            "Compare the visible brand name, footer name, and Organization schema name.",
            "Update the published values so they refer to the same organization name.",
            "Recrawl after publishing the change.",
        ),
        ("trust.consistency.organization_name",),
        effort="small",
        impact="low",
    ),
    rule(
        "trust.review_author_consistency",
        "Trust",
        "Review author information consistency",
        "Align visible bylines with author structured data.",
        "Potential author information inconsistency was detected. This is not an identity-fraud determination.",
        (
            "Compare the visible author name with Person or Article author markup.",
            "Update the published values so they match.",
            "Recrawl the article after publishing.",
        ),
        ("trust.authorship.inconsistent", "trust.consistency.author_information"),
        effort="small",
        impact="low",
    ),
    rule(
        "trust.review_contact_consistency",
        "Trust",
        "Review published contact details",
        "Review contact emails and other contact details for consistent presentation.",
        "Potential contact-information inconsistency was detected across crawled pages. This is not a fraud determination.",
        (
            "Compare footer, contact page, and structured-data contact values.",
            "Publish a consistent contact method for visitors.",
            "Recrawl after publishing.",
        ),
        ("trust.consistency.contact_information",),
        effort="small",
        impact="low",
    ),
]
