from backend.recommendations.registry import rule

RULES = [
    rule(
        "uiux.improve_navigation",
        "UI/UX",
        "Improve primary navigation",
        "Add or expose primary navigation on viewports where none was detected.",
        "Primary navigation helps users move between sections of the site. Affected viewports currently have no detected navigation landmark or equivalent.",
        (
            "Provide a visible navigation region on each affected viewport.",
            "Include links to the primary sections of the site.",
            "Confirm the navigation remains usable at the scanned viewport widths.",
        ),
        ("uiux.navigation.missing",),
        effort="large",
        impact="high",
    ),
    rule(
        "uiux.fix_horizontal_overflow",
        "UI/UX",
        "Fix horizontal overflow",
        "Prevent page content from extending beyond the scanned viewport widths.",
        "Horizontal overflow forces sideways scrolling and can hide content on smaller screens.",
        (
            "Inspect elements that are wider than the viewport.",
            "Allow containers to shrink, wrap, or scroll locally instead of expanding the page.",
            "Recheck the layout at the scanned viewport widths.",
        ),
        ("uiux.resp.001", "uiux.resp.002"),
        effort="medium",
        impact="high",
    ),
    rule(
        "uiux.improve_primary_cta",
        "UI/UX",
        "Improve the primary call to action",
        "Make a primary next-step control visible on pages or viewports where none was detected.",
        "A prominent action control helps users identify the next step on the page. Absence of a detected CTA is not automatically a conversion failure.",
        (
            "Identify the intended primary next step for the page, if one exists.",
            "Present that step as a visible button or link.",
            "Keep the control unclipped and large enough to use at the scanned viewport.",
        ),
        ("uiux.cta.001", "uiux.cta.002", "uiux.cta.003"),
        effort="medium",
        impact="medium",
    ),
    rule(
        "uiux.improve_text_legibility",
        "UI/UX",
        "Improve text legibility",
        "Increase text that is smaller than the configured viewport threshold.",
        "Very small text is harder to read, especially on smaller screens. This is a measured size observation, not a design judgment.",
        (
            "Identify text below the configured minimum size on the affected viewports.",
            "Increase body and control text to a readable size.",
            "Recheck wrapping so larger text does not introduce overflow.",
        ),
        ("uiux.type.001",),
        effort="small",
        impact="medium",
    ),
    rule(
        "uiux.improve_forms",
        "UI/UX",
        "Improve form usability",
        "Address form controls that are missing labels, names, or usable submit actions.",
        "Forms that lack labels or a usable submit control are harder to complete. This is a usability observation from the scanned viewport.",
        (
            "Associate a visible label with each form control.",
            "Ensure submit controls have accessible, visible names.",
            "Check that required fields and grouping are understandable without extra context.",
        ),
        ("uiux.form.usability", "uiux.form.003"),
        effort="medium",
        impact="medium",
    ),
]
